### ISSUE TITLE
Assets/Examples/Example1/src/Program.cs(115,17): error CS0117: `System.Console' does not contain a definition for `KeyAvailable'

### ISSUE THREAD

**Issue by playbug** [rocwood/Entitas-Lite#2]
Assets/Examples/Example1/src/Program.cs(115,17): error CS0117: `System.Console' does not contain a definition for `KeyAvailable'

**Comment by rocwood** [comment]
Example1 is a console app, which could be built & run under vs2015/vs2017.
I've update the source of Example1 to support Unity now.   Take a try?
